In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"]=100

df = pd.read_excel(r"C:\Users\chand\Python\new_project\KnS_libs\FileList (2).xlsx")
# print(df["Posting_Date"].dtype)
# print(df["Posting_Date"].head(10))
df["Posting_Date"] = pd.to_datetime(df["Posting_Date"])
# df["Posting_Date"] = pd.to_datetime(df["Posting_Date"], format="%d/%mm/%Y %H:%M:%S")
df["Post_Date"] = df["Posting_Date"].dt.date
df["Post_time"] = df["Posting_Date"].dt.time
# df["Posting_Date"] = pd.to_datetime(df["Posting_Date"], format="%d/%m/%Y")

df.head()

# df.info()

,Posting_Date,File_No,Client_Name,Application_No,FeeType,OfficalFees_Activity,OfficalFees_SubActivity,CBR_Number,Amount,Attorney_Name,Created_By,Compliance_Docketed_By,Copliance_Verified_By,Compliance_Docketed_By.1,Entry_Status,Compliance_Remarks,Compliance_Remarks_Others,Post_Date,Post_time
0,2026-07-27 07:41:56,IP94775,ITOH PATENT ATTORNEY CORPORATION,NaN,Cash Entry,NEW PATENT APPLICATION,PCT NATIONAL PHASE APPLICATION WITH RFE,46815,46399.86,Yameeni Sarothia,Vipin,,,,PENDING,NaN,NaN,2026-07-27,07:41:56
1,2026-07-27 07:41:56,IP96401,QUALCOMM INCORPORATED,NaN,Cash Entry,NEW PATENT APPLICATION,DIVISIONAL PCT NATIONAL PHASE APPLICATION WITH...,32178,85600.32,Puja Raghav,Vipin,,,,PENDING,NaN,NaN,2026-07-27,07:41:56
2,2026-07-27 07:41:56,IP95471,Centre for Industrial Consultancy,NaN,Cash Entry,NEW PATENT APPLICATION,"ORDINARY APPLICATION COMPLETE, RFE AND RELEVAN...",60969,8480.00,Anjali Singh,Vipin,,,,PENDING,NaN,NaN,2026-07-27,07:41:56
3,2026-07-27 07:41:56,IP96610,DEQI Intellectual Property Law Corporation,NaN,Cash Entry,NEW PATENT APPLICATION,PCT NATIONAL PHASE APPLICATION WITH RFE,46932,95199.78,Neilotpal Mukhopadhyay,Vipin,,,,PENDING,NaN,NaN,2026-07-27,07:41:56
4,2026-07-27 07:41:56,IP51401,Alabaster Research and Technologies,201921050175,Non-Cash,FORM 30 NON CASH,"S21/R24B, R24CFER/SER RESPONSE",61502,0.00,Prashant Shrihari Auti,Vipin,,,,PENDING,NaN,NaN,2026-07-27,07:41:56

In [2]:
df.isnull().sum()

Posting_Date                     0
File_No                          0
Client_Name                      0
Application_No                 881
FeeType                          0
OfficalFees_Activity            45
OfficalFees_SubActivity         57
CBR_Number                      65
Amount                           0
Attorney_Name                    1
Created_By                       0
Compliance_Docketed_By           0
Copliance_Verified_By            0
Compliance_Docketed_By.1         0
Entry_Status                     0
Compliance_Remarks           18640
Compliance_Remarks_Others    70017
Post_Date                        0
Post_time                        0
dtype: int64

In [3]:
# df.insert(1, "Post_Date", df.pop("Post_Date"))
# df.insert(2, "Post_time", df.pop("Post_time"))
cols = ["Post_Date", "Post_time"]+[c for c in df.columns if c not in["Post_Date","Post_time"]]
df = df[cols]
df.isnull().sum()

Post_Date                        0
Post_time                        0
Posting_Date                     0
File_No                          0
Client_Name                      0
Application_No                 881
FeeType                          0
OfficalFees_Activity            45
OfficalFees_SubActivity         57
CBR_Number                      65
Amount                           0
Attorney_Name                    1
Created_By                       0
Compliance_Docketed_By           0
Copliance_Verified_By            0
Compliance_Docketed_By.1         0
Entry_Status                     0
Compliance_Remarks           18640
Compliance_Remarks_Others    70017
dtype: int64

In [4]:
list(enumerate(df.columns))

[(0, 'Post_Date'),
 (1, 'Post_time'),
 (2, 'Posting_Date'),
 (3, 'File_No'),
 (4, 'Client_Name'),
 (5, 'Application_No'),
 (6, 'FeeType'),
 (7, 'OfficalFees_Activity'),
 (8, 'OfficalFees_SubActivity'),
 (9, 'CBR_Number'),
 (10, 'Amount'),
 (11, 'Attorney_Name'),
 (12, 'Created_By'),
 (13, 'Compliance_Docketed_By'),
 (14, 'Copliance_Verified_By'),
 (15, 'Compliance_Docketed_By.1'),
 (16, 'Entry_Status'),
 (17, 'Compliance_Remarks'),
 (18, 'Compliance_Remarks_Others')]

In [5]:
nul_col = df.columns[df.isnull().all()]
print(nul_col)

Index([], dtype='str')

In [7]:
# df = df.dropna(axis=1, how="all")
df.head()

,Post_Date,Post_time,Posting_Date,File_No,Client_Name,Application_No,FeeType,OfficalFees_Activity,OfficalFees_SubActivity,CBR_Number,Amount,Attorney_Name,Created_By,Compliance_Docketed_By,Copliance_Verified_By,Compliance_Docketed_By.1,Entry_Status,Compliance_Remarks,Compliance_Remarks_Others
0,2026-07-27,07:41:56,2026-07-27 07:41:56,IP94775,ITOH PATENT ATTORNEY CORPORATION,NaN,Cash Entry,NEW PATENT APPLICATION,PCT NATIONAL PHASE APPLICATION WITH RFE,46815,46399.86,Yameeni Sarothia,Vipin,,,,PENDING,NaN,NaN
1,2026-07-27,07:41:56,2026-07-27 07:41:56,IP96401,QUALCOMM INCORPORATED,NaN,Cash Entry,NEW PATENT APPLICATION,DIVISIONAL PCT NATIONAL PHASE APPLICATION WITH...,32178,85600.32,Puja Raghav,Vipin,,,,PENDING,NaN,NaN
2,2026-07-27,07:41:56,2026-07-27 07:41:56,IP95471,Centre for Industrial Consultancy,NaN,Cash Entry,NEW PATENT APPLICATION,"ORDINARY APPLICATION COMPLETE, RFE AND RELEVAN...",60969,8480.00,Anjali Singh,Vipin,,,,PENDING,NaN,NaN
3,2026-07-27,07:41:56,2026-07-27 07:41:56,IP96610,DEQI Intellectual Property Law Corporation,NaN,Cash Entry,NEW PATENT APPLICATION,PCT NATIONAL PHASE APPLICATION WITH RFE,46932,95199.78,Neilotpal Mukhopadhyay,Vipin,,,,PENDING,NaN,NaN
4,2026-07-27,07:41:56,2026-07-27 07:41:56,IP51401,Alabaster Research and Technologies,201921050175,Non-Cash,FORM 30 NON CASH,"S21/R24B, R24CFER/SER RESPONSE",61502,0.00,Prashant Shrihari Auti,Vipin,,,,PENDING,NaN,NaN

In [9]:
for i, col in enumerate(df.columns):
    print(i, col)

0 Post_Date
1 Post_time
2 Posting_Date
3 File_No
4 Client_Name
5 Application_No
6 FeeType
7 OfficalFees_Activity
8 OfficalFees_SubActivity
9 CBR_Number
10 Amount
11 Attorney_Name
12 Created_By
13 Compliance_Docketed_By
14 Copliance_Verified_By
15 Compliance_Docketed_By.1
16 Entry_Status
17 Compliance_Remarks
18 Compliance_Remarks_Others

In [10]:
df = df.drop(columns=["Post_time"])